### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by bibek-maharjan** [chesterchong/TickTick-Windows-4.02-Crack#1]
Error message while installing with 3.8.0.0

![image](https://user-images.githubusercontent.com/76084262/131633618-2cf6c315-0da6-479f-933e-3f2ec64343c5.png)
![image](https://user-images.githubusercontent.com/76084262/131633623-8156cc68-4d4e-457e-83a9-885d96fcef09.png)

**Comment by chesterchong** [comment]
It was due to incompatible version between package and executable file. Do it again with the latest updated files, it should be okay right now.
