### ISSUE TITLE
Hey, Chester! :)

### ISSUE THREAD

**Issue by DostoievskiF** [chesterchong/TickTick-Windows-4.02-Crack#2]
### **Hi, Chester! xD**
Is there some virus/malware in the Android APK or in Windows?

Thank you for your great work, brother! I would love to be able to pay for the app, but unfortunately I can't afford it. :( 

I'm afraid you might be trying to teach a lesson to users looking for free versions of paid apps. 
Sorry for the distrust, my brother. 
I would be very happy if you could answer me, indicating some way to check for viruses or not. :)

**Comment by chesterchong** [comment]
Hey, there is no virus/malware contained. Feel free to decompile and disassemble the files and search for the user model.

**Comment by Koushikphy** [comment]
it seems you modified the user model for the windows app to unlock the premium features. Can you tell me how did you unlock the andorid app?
